version: '3.7'

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    restart: always
  web:
    build: .
    command: node app.js
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - db